apply black formatting
WISVCH/dienst2 pull request #274
Opened 2020-10-06 14:13 UTC by julian9499

2020-10-06 17:25 UTC, praseodym requested changes
Volgens mij zitten er meer wijzigingen in deze PR dan alleen formatting

2020-10-06 17:25 UTC, praseodym commented on dienst2/settings.py
> +OIDC_LDAP_ACCESS_GROUP = env("OIDC_LDAP_ACCESS_GROUP", default="hoothub")
eeuh?

2020-10-06 17:25 UTC, praseodym requested changes

2020-10-06 17:25 UTC, praseodym commented on ldb/formTemplates/entity.py
> +class Entity(models.Model):
Nieuwe file in een formatting PR?

2020-10-07 08:45 UTC, julian9499 commented
Ik heb de changes die perongeluk mee gecommit waren geremoved

2020-10-09 11:07 UTC, praseodym requested changes

2020-10-09 11:07 UTC, praseodym commented on docker-entrypoint-dev.sh
> -#!/bin/bash
waarom is deze file verwijderd?

2020-10-09 11:07 UTC, praseodym commented on package.json
> -{
En deze file?

2020-10-09 11:32 UTC, julian9499 commented on docker-entrypoint-dev.sh
> -#!/bin/bash
reverted

2020-10-09 12:14 UTC, praseodym approved these changes

2020-10-12 08:54 UTC, jgadelange approved these changes

2020-10-12 09:50 UTC, merged